export const FETCH_GUIDELINES_REQUEST = 'FETCH_GUIDELINES_REQUEST';
export const FETCH_GUIDELINES_SUCCESS = 'FETCH_GUIDELINES_SUCCESS';
export const FETCH_GUIDELINES_ERROR = 'FETCH_GUIDELINES_ERROR';
