export const FETCH_GUIDELINES_REQUEST = 'FETCH_GUIDELINES_REQUEST';
export const FETCH_GUIDELINES_SUCCESS = 'FETCH_GUIDELINES_SUCCESS';
export const FETCH_GUIDELINES_ERROR = 'FETCH_GUIDELINES_ERROR';

export const ADD_GUIDELINES_REQUEST = 'ADD_GUIDELINES_REQUEST';
export const ADD_GUIDELINES_SUCCESS = 'ADD_GUIDELINES_SUCCESS';
export const ADD_GUIDELINES_ERROR = 'ADD_GUIDELINES_ERROR';

export const ADD_GUIDELINE = 'ADD_GUIDELINE';
